### ISSUE TITLE
Links to other resources

### ISSUE THREAD

**Issue by Symbian9** [mrRosset/Symbian-Archive#1]
Here are some usefull links, collected by me

**Software**
* http://symbian.host-ed.me
  * http://symbian.host-ed.me/links.html

**Documentation**
* https://github.com/trufanov-nok/SymbianBook_ru
* http://read.pudn.com/downloads159/sourcecode/comm/symbian/709608/Quick%20Recipes%20on%20Symbian%20OS%20Mastering%20C%2B%2B%20Mobile%20Development.pdf
* http://mobiledevices.kom.aau.dk/fileadmin/mobiledevices/MDD07/slides/Open_C_MDD_2007.pdf

P.S.: I will add more links soon

**Comment by mrRosset** [comment]
Thank you very much.
I will look into the links and documentations to add them. For the second book I will probably not add it since it's still on the market and there is no authorization from the author.

**Comment by mrRosset** [comment]
I've added all of those to their respectives sections of the website.
85b3b28f534d15e288989953cdbe4c7ca17ab725
2a00c52fbcdff87f6885eed858d4aea9cad2638e
b4ddf52ec4e032a04f486805ebca4cd050899d15

**Comment by Symbian9** [comment]
Thanks.

Also I have some other usefull links.
So, where I should post them later: in current issue or in newly created issues?

**Comment by mrRosset** [comment]
If that's not a problem, create a new issue please
