### ISSUE TITLE
Ruby for Symbian

### ISSUE THREAD

**Issue by Symbian9** [mrRosset/Symbian-Archive#2]
* http://www.gredia.eu/upload/Gredia_Ruby.pdf
* https://github.com/sj26/ruby-1.9.3-p0/tree/master/symbian
* https://www.ruby-lang.org/en/news/2010/08/18/ruby-1-9-2-released/

**Comment by mrRosset** [comment]
Thank you.
This was added to the ruby section
d4f77c5918bf6d3bc1f14c9e7f2353322aeae690
cc9929886395150ae2d35696e563b9798fc13ec9
26bea96b5e4e1911622111b36f73f645476925fb
