### ISSUE TITLE
developer.nokia.com community wiki archieve content isn't accessable via search engines

### ISSUE THREAD

**Issue by trufanov-nok** [mrRosset/Symbian-Archive#21]
Today I spent toooo much time trying to find J2MEBridge 1 0.zip and J2MEBridgeExamples.zip from old Nokia Developer Wiki. I finally found them in [developernokiacom_community_wiki-20140701-wikidump.7z](https://ia802508.us.archive.org/14/items/wiki-developernokiacom_community_wiki/developernokiacom_community_wiki-20140701-wikidump.7z) but only after I downloaded and took a look into it.
 I guess it's referenced on your site but definitely not fully indexed by search engines as there are no working links to J2MEBridge 1 0.zip with apibridge.jar. My suggestion is to generate a list of all content in it and publish it in txt somewhere on your site to make it more searchable by filenames. There are about 2 Gb of code samples in zip and docs in pdf.

**Comment by trufanov-nok** [comment]
I've made a simple list with linux' `tree -h` tool [developernokiacom_community_wiki-20140701-wikidump.zip](https://github.com/mrRosset/Symbian-Archive/files/2511685/developernokiacom_community_wiki-20140701-wikidump.zip)

**Comment by mrRosset** [comment]
Sorry I don't have much time currently to focus on this projet. If you want I accept pull requests. But considering the stuff on the website in total weight more than 40Gb this idea would be a lot of work
