### ISSUE TITLE
Dictionaries for Symbian

### ISSUE THREAD

**Issue by Symbian9** [mrRosset/Symbian-Archive#3]
I collect most of them here
* https://github.com/goldendict/goldendict/issues/765

But its not a full list, so maybe later will add more

**Comment by mrRosset** [comment]
Thanks,
Added in a8e311bc6d5ff22735fe63ab7468f8c445459837

**Comment by mrRosset** [comment]
I wanted to add your name on the list of thanks on the homepage, should I use Symbian9 or AppSoft4 (or something else) ?

**Comment by Symbian9** [comment]
Think, you could use 'AppSoft4' ;-)
